trigger:
  branches:
    include: [ '*' ]
stages:
  - stage: Build
    variables:
      BuildConfiguration: Release
    jobs:
      - job:
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: '**/*.csproj'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: '**/*.csproj'
              arguments: '-c $(BuildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test
              nobuild: true
              publishTestResults: true
              projects: '**/*.Tests.csproj'
              arguments: '-c $(BuildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: Package
            inputs: 
              command: 'pack'
              includesymbols: true
              nobuild: true
              configuration: $(BuildConfiguration)
              outputDir: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  - stage: Nightly
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment:
        environment: Nightly
        strategy: 
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: Push to NuGet Feed
                  inputs:
                    command: 'push'
                    packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                    nuGetFeedType: 'internal'
                    publishVstsFeed: 'd709a194-9ce6-4530-a6e2-22368bf72347/0d984cd1-0749-4fe0-b7b3-debfb4ba4890'
                    allowPackageConflicts: true
  - stage: Public
    dependsOn: Build
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/v'), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment:
        environment: NuGet
        strategy: 
          runOnce:
            deploy:
              steps:
              - task: NuGetCommand@2
                inputs:
                  command: 'push'
                  packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                  nuGetFeedType: 'external'
                  publishFeedCredentials: 'NuGet.org'
